### PR TITLE
Use rbenv instead of ppa WIP

### PR DESCRIPTION
**Pull request by enricostano**
TODO:
- [ ] check ruby version
- [ ] rbenv shims in $PATH
- [ ] choose how to install global gems like bundler

### CODE REVIEW

**Comment by enricostano** [comment]
Maybe we can take inspiration from this https://github.com/aleks/ansible-rails

**Comment by saverio-kantox** [comment]
Really? I though that it was much better to use the PPA.... ;)

**Comment by enricostano** [comment]
@saverio-kantox I only talk with @rewritten :trollface:

**Comment by saverio-kantox** [comment]
🙊

**Comment by andresgutgon** [comment]
Lol, another bi-polar dev

**Comment by rewritten** [comment]
Who's that guy that tries to disguise as me???? There is only one @rewritten, and it's me.

By the way, I though that it was much better to use the PPA.... ;)

**Comment by enricostano** [comment]
LOL

@rewritten PPA approach in general is good, the problem is that the only ruby PPA that is production ready-ish is the BrightBox one.... and they deliberately drop minor versions every time a new minor version is released. Example:

You have the `2.3.1` in your provisioning and they drop it since there is a `2.3.2` available now. They don't maintain minor versions basically and that's painful. So... we're switching to `rbenv` or some other lightweigth ruby version manager, sadly.

The other option would be to compile ruby versions by ourselves and publish them to a PPA... no thanks. At least for now.

Sorry, this explaination should have been in the PR description. 🙏

**Comment by enricostano** [comment]
Not using this repo anymore.

**Pull request closed without merging**
